language: php
sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  include:
    - php: 5.4
      sudo: required
      services:
          - docker
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction
  - docker pull registry:latest
  - docker run -p 5000:5000 -d registry

script:
  - bin/phpunit

after_script:
  - sudo cat /var/log/upstart/docker.log
