php56:
  image: phundament/php-one:5.6-fpm
  command: sh -c 'composer install && bin/phpunit'
  volumes:
    - ./:/app
    - /var/run/docker.sock:/var/run/docker.sock
php70:
  image: phundament/php-one:7.0-fpm
  command: sh -c 'composer install && bin/phpunit'
  volumes:
    - ./:/app
    - /var/run/docker.sock:/var/run/docker.sock