site_name: Docker PHP
site_url:  http://docker-php.readthedocs.org/
site_description: A Docker client in PHP
repo_url: https://github.com/stage1/docker-php

pages:
  - Home: index.md
  - Docker PHP:
      - Installation: installation.md
      - Connecting to Docker: connection.md
      - Basic Usage: basic.md
  - Containers:
      - Basic Usage: container/basic.md
      - Running a container: container/run.md
  - Images:
      - Basic Usage: image/basic.md
      - Build an image: image/build.md
      - Create (or pull) an image: image/create.md
      - Push an image: image/push.md
  - Exec: exec/basic.md
  - Volume: volume/basic.md
  - Network: network/basic.md
  - Misc: misc/basic.md
